library('tidyverse')
library('ggplot2')
library('dplyr')
library('ggpubr')
library('see')
library('cowplot')
library('rstatix')
library('R.utils')
library('psych')
library('nlme')
library("car")
library("lme4")

setwd('E://Efflux_Paper//Data//For_Manuscript//Excel_Files//Additional_AB_Analysis//')
data <- read.csv(file = 'E://Efflux_Paper//Data//For_Manuscript//Excel_Files//Additional_AB_Analysis//20260411_Data_from_Jari.csv', header=TRUE, sep=',')
directory_name = "Output_Stats"
dir.create(directory_name)
  
OB_desc <- describeBy(data$OB, data$Group, mat = TRUE) 
OB_aov <- aov(data = data, formula = OB ~ Group)
summary(OB_aov)
OB_aov_shapiro_residuals = shapiro_test(residuals(OB_aov))
OB_wilcoxon = wilcox.test(OB~Group, data=data, paired = FALSE, p.adjust.method = "BH")

NT_desc <- describeBy(data$NT, data$Group, mat = TRUE) 
NT_aov <- aov(data = data, formula = NT ~ Group)
summary(NT_aov)
NT_aov_shapiro_residuals = shapiro_test(residuals(NT_aov))
NT_wilcoxon = wilcox.test(NT~Group, data=data, paired = FALSE, p.adjust.method = "BH")

NTvOB_desc <- describeBy(data$NT_v_OB, data$Group, mat = TRUE) 
NTvOB_aov <- aov(data = data, formula = NT_v_OB ~ Group)
summary(NTvOB_aov)
NTvOB_aov_shapiro_residuals = shapiro_test(residuals(NTvOB_aov))
NTvOB_wilcoxon = wilcox.test(NT_v_OB~Group, data=data, paired = FALSE, p.adjust.method = "BH")

#Define filename
filename_txt = paste0(directory_name,'//Final_Inferential_Statistics_Normalized.txt') 
filename_txt = file(filename_txt, 'w')

cat("############################################# OB #############################################\n", file = filename_txt)
cat("\n\n OB Descriptives\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(OB_desc , file = filename_txt, append = TRUE)
cat("\n\n OB ANOVA\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(summary(OB_aov), file = filename_txt, append = TRUE)
cat("\n\n OB ANOVA Residual Shapiro-Wilk Test\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(OB_aov_shapiro_residuals, file = filename_txt, append = TRUE)
cat("\n\n OB Wilcoxon Test\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(OB_wilcoxon, file = filename_txt, append = TRUE)
cat("############################################# NT #############################################\n", file = filename_txt)
cat("\n\n NT Descriptives\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(NT_desc , file = filename_txt, append = TRUE)
cat("\n\n NT ANOVA\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(summary(NT_aov), file = filename_txt, append = TRUE)
cat("\n\n OB ANOVA Residual Shapiro-Wilk Test\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(NT_aov_shapiro_residuals, file = filename_txt, append = TRUE)
cat("\n\n OB Wilcoxon Test\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(NT_wilcoxon, file = filename_txt, append = TRUE)
cat("############################################# OB vs. NT #############################################\n", file = filename_txt)
cat("\n\n NT vs OB Descriptives\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(NTvOB_desc , file = filename_txt, append = TRUE)
cat("\n\n NT vs OB ANOVA\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(summary(NTvOB_aov), file = filename_txt, append = TRUE)
cat("\n\n NT vs OB ANOVA Residual Shapiro-Wilk Test\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(NTvOB_aov_shapiro_residuals, file = filename_txt, append = TRUE)
cat("\n\n NT vs OB Wilcoxon Test\n", file = filename_txt, append=TRUE, sep = "\n")
captureOutput(NTvOB_wilcoxon, file = filename_txt, append = TRUE)
